language: node_js
node_js:
- "11"

script:
- echo "skipping tests"

deploy:
  provider: script
  script: "npm run push"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - harunsokullu@gmail.com
    on_success: change
    on_failure: always